export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';

export const MAPSELF_GET_SUCCESS='MAPSELF_GET_SUCCESS';
export const MAPSELF_GET_TABLE='MAPSELF_GET_TABLE';
export const MAPSELF_SET_SEARCHTERM='MAPSELF_SET_SEARCHTERM';
export const MAPSELF_SET_SEARCHPAGE='MAPSELF_SET_SEARCHPAGE';
export const MAPSELF_SET_SEARCHID='MAPSELF_SET_SEARCHID';


export const DATA_GET_TABLE='DATA_GET_TABLE';
export const DATA_GET_IMAGES='DATA_GET_IMAGES';
export const DATA_SET_SEARCHTERM='DATA_SET_SEARCHTERM';
export const DATA_SET_SEARCHPAGE='DATA_SET_SEARCHPAGE';
export const DATA_SET_SEARCHID='DATA_SET_SEARCHID';


export const CASE_GET_TABLE='CASE_GET_TABLE';
export const CASE_SET_SEARCHTERM='CASE_SET_SEARCHTERM';
export const CASE_SET_SEARCHPAGE='CASE_SET_SEARCHPAGE';
export const CASE_UPDATE='CASE_UPDATE';

export const CASETABLE_GET_TABLE='CASETABLE_GET_TABLE';
export const CASETABLE_SET_SEARCHTERM='CASETABLE_SET_SEARCHTERM';
export const CASETABLE_SET_SEARCHPAGE='CASETABLE_SET_SEARCHPAGE';
export const CASETABLE_SET_SEARCHID='CASETABLE_SET_SEARCHID';


export const TRACK_GET_TABLE='TRACK_GET_TABLE';
export const TRACK_SET_SEARCHTERM='TRACK_SET_SEARCHTERM';
export const TRACK_SET_SEARCHPAGE='TRACK_SET_SEARCHPAGE';
export const TRACK_UPDATE='TRACK_UPDATE';

export const TRACKRESULT_GET_TABLE= 'TRACKRESULT_GET_TABLE';
export const TRACKRESULT_SET_SEARCHTERM= 'TRACKRESULT_SET_SEARCHTERM';
export const TRACKRESULT_SET_SEARCHPAGE= 'TRACKRESULT_SET_SEARCHPAGE';
export const TRACKRESULT_SET_SEARCHID= 'TRACKRESULT_SET_SEARCHID';
export const TRACKRESULT_UPDATE='TRACKRESULT_UPDATE';
export const TRACKRESULT_GET_MAPDATA='TRACKRESULT_GET_MAPDATA';



export const CHART_GET_TABLE='CHART_GET_TABLE';
export const CHART_SET_SEARCHTERM='CHART_SET_SEARCHTERM';